services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "112233" 
      POSTGRES_DB: db_depression
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_depression"]
      interval: 10s
      timeout: 5s
      retries: 5

  pipeline_app: 
    build: .
    container_name: pipeline_app
    depends_on:
      postgres_db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./files:/files 
    environment:
      - DB_HOST=postgres_db
      - DB_NAME=db_depression
      - DB_USER=postgres
      - DB_PASS=112233
      - DB_PORT=5432
    command: python -u run_pipeline.py

volumes:
  postgres_data: